### ISSUE TITLE
Bug: local tests KV storage read only

### ISSUE THREAD

**Issue by jdddog** [The-Academic-Observatory/coki-oa-web#76]
When running `workers-api` tests locally, the error ` TypeError: Unable to put into read-only namespace` is thrown, which doesn't get thrown when tests run in Github Actions.

```bash
 FAIL  src/router.test.ts (452.745 s)
  ✓ test handleRequest 404 (5 ms)
  ✓ test handleRequest search (8 ms)
  ✕ test handleRequest country
  ✕ test handleRequest institution (1 ms)
  ✓ test handleRequest countries: order key stats.p_outputs_open (313 ms)
  ✓ test handleRequest countries: order key name (285 ms)
  ✓ test handleRequest countries: ids (3 ms)
  ✓ test handleRequest countries: subregions (22 ms)
  ✓ test handleRequest countries: regions (24 ms)
  ✓ test handleRequest countries: minNOutputs, maxNOutputs (6 ms)
  ✓ test handleRequest countries: stats.p_outputs (57 ms)
  ✓ test handleRequest institutions: order (406497 ms)
  ✓ test handleRequest institutions: ids (12 ms)
  ✓ test handleRequest institutions: countries (188 ms)
  ✓ test handleRequest institutions: institution_type (36003 ms)
  ✕ test downloadZip country (1 ms)
  ✕ test downloadZip institution (1 ms)
  ✕ test downloadZip country NotFound
  ✕ test downloadZip institution NotFound (1 ms)

  ● test handleRequest country

    TypeError: Unable to put into read-only namespace

      67 | test("test handleRequest country", async () => {
      68 |   // Put data into KV namespace for testing
    > 69 |   await env.__STATIC_CONTENT.put("country/NZL.json", fs.readFileSync("./public/country/NZL.json", "utf-8"));
         |                              ^
      70 |
      71 |   let res = await handleRequest(new Request(`${host}/country/NZL`), env, ctx);
      72 |   let json = await res.json();

      at FilteredKVNamespace.put (node_modules/@miniflare/sites/src/filtered.ts:64:13)
      at Object.<anonymous> (src/router.test.ts:69:30)

  ● test handleRequest institution

    TypeError: Unable to put into read-only namespace

      77 | test("test handleRequest institution", async () => {
      78 |   // Put data into KV namespace for testing
    > 79 |   await env.__STATIC_CONTENT.put(
         |                              ^
      80 |     "institution/030cszc07.json",
      81 |     fs.readFileSync("./public/institution/030cszc07.json", "utf-8"),
      82 |   );

      at FilteredKVNamespace.put (node_modules/@miniflare/sites/src/filtered.ts:64:13)
      at Object.<anonymous> (src/router.test.ts:79:30)

  ● test downloadZip country

    TypeError: Unable to put into read-only namespace

      330 |
      331 |   // //Put data into KV namespace for testing
    > 332 |   await env.__STATIC_CONTENT.put("country/NZL.json", fs.readFileSync("./public/country/NZL.json", "utf-8"));
          |                              ^
      333 |
      334 |   // Make download request
      335 |   let res = await handleRequest(new Request(`${host}/download/country/NZL`), env, ctx);

      at FilteredKVNamespace.put (node_modules/@miniflare/sites/src/filtered.ts:64:13)
      at Object.<anonymous> (src/router.test.ts:332:30)

  ● test downloadZip institution

    TypeError: Unable to put into read-only namespace

      362 |
      363 |   // // Put data into KV namespace for testing
    > 364 |   await env.__STATIC_CONTENT.put(
          |                              ^
      365 |     "institution/030cszc07.json",
      366 |     fs.readFileSync("./public/institution/030cszc07.json", "utf-8"),
      367 |   );

      at FilteredKVNamespace.put (node_modules/@miniflare/sites/src/filtered.ts:64:13)
      at Object.<anonymous> (src/router.test.ts:364:30)

  ● test downloadZip country NotFound

    TypeError: Unable to put into read-only namespace

      394 | test("test downloadZip country NotFound", async () => {
      395 |   // Put example country data into KVNamespace.
    > 396 |   await env.__STATIC_CONTENT.put("country/NZL.json", fs.readFileSync("./public/country/NZL.json", "utf-8"));
          |                              ^
      397 |
      398 |   // Assert that API returns a 404 for a bad country ID
      399 |   let resCountry = await handleRequest(new Request(`${host}/download/country/ABC`), env, ctx);

      at FilteredKVNamespace.put (node_modules/@miniflare/sites/src/filtered.ts:64:13)
      at Object.<anonymous> (src/router.test.ts:396:30)

  ● test downloadZip institution NotFound

    TypeError: Unable to put into read-only namespace

      403 | test("test downloadZip institution NotFound", async () => {
      404 |   // Put example data into KVNamespace.
    > 405 |   await env.__STATIC_CONTENT.put(
          |                              ^
      406 |     "institution/030cszc07.json",
      407 |     fs.readFileSync("./public/institution/030cszc07.json", "utf-8"),
      408 |   );

      at FilteredKVNamespace.put (node_modules/@miniflare/sites/src/filtered.ts:64:13)
      at Object.<anonymous> (src/router.test.ts:405:30)

```

**Comment by jdddog** [comment]
This occurs when a `wrangler.toml` file is in the workers-api directory.
